<SettingsScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 20

        Label:
            font_name: 'Roboto'
            font_size: 180
            pos: 10, 50
            markup: True
            text: '00.00.[size=40]00[/size]'


        BoxLayout:
            orientation: 'horizontal'
            height: 90
            padding: 20
            spacing: 20
            size_hint: (1, None)
